# And!Or Designs
# Basement Office Laundry Crawl Space Fan Control
# 2022-07-29 v0.1

esphome:
  name: ardn-ofc-fan

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "###for public presentation###"

ota:
  password: "###for public presentation###"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "###for public presentation###"
    password: "###for public presentation###"

captive_portal:
    
output:
  - platform: gpio
    pin: GPIO 32
    id: fanControl
    
fan:
  - platform: binary
    output: fanControl
    restore_mode: ALWAYS_OFF
    name: "Office Crawl Space Fan"
